W6D3/skeleton/config/routes.rb
AjaxTwitter::Application.routes.draw do
  resource :feed, only: [:show]
  resource :session, only: [:create, :destroy, :new]
  resources :tweets, only: [:create]
  resources :users, only: [:create, :new, :show] do
    get "search", on: :collection

    resource :follow, only: [:create, :destroy]
  end

  root to: redirect("/feed")
end

W6D3/skeleton/app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :followee, class_name: "User"
  belongs_to :follower, class_name: "User"

  validates :followee, :follower, presence: true
  validates :follower, uniqueness: { scope: :followee }
end

W6D3/skeleton/app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user

  validates :tweet, :user, presence: true
  validates :user, uniqueness: { scope: :tweet }
end

W6D3/skeleton/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_many :mentions
  has_many :mentioned_users, through: :mentions, source: :user
  belongs_to :user

  validates :content, :user, presence: true
end

W6D3/skeleton/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  has_many :in_follows, class_name: "Follow", foreign_key: "followee_id"
  has_many :out_follows, class_name: "Follow", foreign_key: "follower_id"
  has_many :followers, through: :in_follows, source: :follower
  has_many :followees, through: :out_follows, source: :followee
  has_many :tweets, dependent: :destroy

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username
    return nil if user.nil?

    # check user's password
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def feed_tweets(limit = nil, max_created_at = nil)
    @tweets = Tweet
      .joins(:user)
      .joins("LEFT OUTER JOIN follows ON users.id = follows.followee_id")
      .where("tweets.user_id = :id OR follows.follower_id = :id", id: self.id)
      .order("tweets.created_at DESC")
      .uniq

    # TODO: How can we use limit/max_created_at here??

    @tweets
  end

  def follows?(user)
    out_follows.exists?(followee_id: user.id)
  end
end

W6D3/skeleton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    User.find_by(session_token: self.session[:session_token])
  end
  helper_method :current_user

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end

  def require_logged_in!
    redirect_to new_session_url if current_user.nil?
  end

  def require_not_logged_in!
    redirect_to feed_url unless current_user.nil?
  end
end

W6D3/skeleton/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :require_logged_in!

  LIMIT = 20

  def show
    @feed_tweets =
      current_user.feed_tweets(LIMIT, params[:max_created_at]).includes(:user)
    
    render :show
  end
end

W6D3/skeleton/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @follow = current_user.out_follows.create!(followee_id: params[:user_id])

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render json: @follow }
    end
  end

  def destroy
    # simulate latency
    sleep(1)

    @follow = current_user.out_follows.find_by(followee_id: params[:user_id])
    @follow.destroy!

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render json: @follow }
    end
  end
end

W6D3/skeleton/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:destroy]

  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to feed_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to new_session_url
  end

  def new
    # presents a login form
    render :new
  end
end

W6D3/skeleton/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      respond_to do |format|
        format.html { render :show }
        format.json { render :show }
      end
    else
      # Lazy: even respond with JSON to invalid HTML request.
      render json: @tweet.errors.full_messages, status: 422
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, mentioned_user_ids: [])
  end
end

W6D3/skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:show]

  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to feed_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = User.includes(tweets: :mentioned_users).find(params[:id])
    render :show
  end

  def search
    
    if params[:query].present?
      @users = User.where("username ~ ?", params[:query])
    else
      @users = User.none
    end

    respond_to do |format|
        format.html { render :search }
        format.json { render :search }
    end
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

W6D3/skeleton/app/helpers/application_helper.rb
module ApplicationHelper
end

W6D3/skeleton/app/views/feeds/show.html.erb
<h1>Welcome <%= current_user.username %>!</h1>

<b>Your Feed!</b>
<ul id="feed">
  <% @feed_tweets.each do |tweet| %>
    <li><%= render "tweets/tweet", tweet: tweet %></li>
  <% end %>
</ul>

<%= render "tweets/form" %>

W6D3/skeleton/app/views/follows/_form.html.erb
<!-- <% if current_user.follows?(user) %>
  <%= button_to "Unfollow", user_follow_url(user), method: :delete %>
<% else %>
  <%= button_to "Follow", user_follow_url(user), method: :post %>
<% end %> -->

<button type="button" class="follow-toggle" data-user-id="<%= user.id %>" data-user-follow-state="<%= current_user.follows?(user) %>">
</button>

W6D3/skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

<ul>
  <li><%= link_to "Feed", feed_url %></li>
  <li><%= link_to "User Search", search_users_url %></li>
</ul>

<% if current_user %>
  <form action="/session" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="submit" value="Logout!">
  </form>
<% end %>

<%= yield %>

</body>
</html>

W6D3/skeleton/app/views/tweets/_form.html.erb
<h2>New Tweet!</h2>
<form action="/tweets" method="POST" class="tweet-compose">
  <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

  <label>
    Content
    <textarea name="tweet[content]"></textarea>
  </label>
  <br>

  <label>
    Mention
    <select name="tweet[mentioned_user_ids][]" class="dropdown">
      <option></option>
      <% User.all.each do |user| %>
        <option value="<%= user.id %>"><%= user.username %></option>
      <% end %>
    </select>
  </label>
  <br>

  <input type="Submit" value="Post Tweet!">
</form>

W6D3/skeleton/app/views/tweets/_tweet.html.erb
<%= tweet.content %>
-- <%= link_to tweet.user.username, user_url(tweet.user.id) %>
-- <%= tweet.created_at %>

<% if tweet.mentioned_users.length > 0 %>
  <ul>
    <% tweet.mentioned_users.each do |mentioned_user| %>
      <li><%= link_to mentioned_user.username, user_url(mentioned_user) %></li>
    <% end %>
  </ul>
<% end %>

W6D3/skeleton/app/views/users/new.html.erb
<h1>Sign up!</h1>

<ul>
  <% @user.errors.full_messages.each do |err_msg| %>
    <li><%= err_msg %></li>
  <% end %>
</ul>

<form action="/users" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
    type="text"
    name="user[username]"
    id="user_username"
    value="<%= @user.username %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>

  <input type="submit" value="Create User!">
</form>

W6D3/skeleton/app/views/users/search.html.erb
<h1>Search!</h1>
<!--
<form action="/users/search" method="GET">
  <input
    type="text"
    name="query"
    value="<%= @query %>">

  <input type="submit" value="Search Users!">
</form>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user_url(user) %>
      <%= render "follows/form", user: user %>
    </li>
  <% end %>
</ul> -->
<nav class="users-search">
  <label>Username
    <input class="searchbar" type="text" name="user[username]">
  </label>

  <ul class="users">
    
  </ul>
</nav>

W6D3/skeleton/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= render "follows/form", user: @user %>

<b>Tweets</b>
<ul>
  <% @user.tweets.each do |tweet| %>
    <li><%= render "tweets/tweet", tweet: tweet %></li>
  <% end %>
</ul>

<b>Followers</b>
<ul>
  <% @user.followers.each do |follower| %>
    <li><%= follower.username %></li>
  <% end %>
</ul>

<b>Followees</b>
<ul>
  <% @user.followees.each do |followee| %>
    <li><%= followee.username %></li>
  <% end %>
</ul>